# NumPy Retail Analytics Assignment

## Business Scenario

**SmartMart Retail Stores** operates five stores across different cities and sells six
major product categories. Management wants to analyse sales performance, expenses,
profits, targets, discounts, inventory and store-level performance using NumPy.

**Run the cells in order** - later questions use arrays created in earlier ones.

# Part 1: Dataset Creation

### Dataset Setup

Create the `stores`, `categories`, `sales_data` and `cost_data` arrays.
Rows represent stores, columns represent product categories.

In [2]:
import numpy as np

stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


# Part 2: Basic Array Understanding

## Question 1: Array Dimensions

Display the number of dimensions, shape, total number of values, data type and memory
occupied by `sales_data`.

`ndim` gives the depth of nesting, `shape` the size along each axis, `size` the total
element count, and `nbytes` the memory in bytes.

In [3]:
print("Number of dimensions :", sales_data.ndim)
print("Shape                :", sales_data.shape)
print("Total number of values:", sales_data.size)
print("Data type            :", sales_data.dtype)
print("Memory occupied      :", sales_data.nbytes, "bytes")
print("Bytes per element    :", sales_data.itemsize)

Number of dimensions : 2
Shape                : (5, 6)
Total number of values: 30
Data type            : int32
Memory occupied      : 120 bytes
Bytes per element    : 4


## Question 2: Store and Category Count

Calculate the total number of stores, product categories and store-category combinations.

The shape tuple gives both counts directly: `shape[0]` is rows (stores) and `shape[1]`
is columns (categories).

In [4]:
total_stores = sales_data.shape[0]
total_categories = sales_data.shape[1]
total_combinations = sales_data.size

print("Total number of stores           :", total_stores)
print("Total number of categories       :", total_categories)
print("Total store-category combinations:", total_combinations)

Total number of stores           : 5
Total number of categories       : 6
Total store-category combinations: 30


## Question 3: Sales Data Type Conversion

Convert `sales_data` into `float32` and `float64`, then compare the memory used by both.

`float32` uses 4 bytes per value and `float64` uses 8, so the same data occupies twice
the memory in `float64`.

In [3]:
sales_float32 = sales_data.astype(np.float32)
sales_float64 = sales_data.astype(np.float64)

print("Original dtype :", sales_data.dtype, "|", sales_data.nbytes, "bytes")
print("float32 dtype  :", sales_float32.dtype, "|", sales_float32.nbytes, "bytes")
print("float64 dtype  :", sales_float64.dtype, "|", sales_float64.nbytes, "bytes")

print("\nfloat64 uses", sales_float64.nbytes - sales_float32.nbytes, "bytes more than float32")

print("\nfloat32 array:")
print(sales_float32)

Original dtype : int32 | 120 bytes
float32 dtype  : float32 | 120 bytes
float64 dtype  : float64 | 240 bytes

float64 uses 120 bytes more than float32

float32 array:
[[ 850000.  420000.  310000.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  310000.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  510000.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  175000.  205000.]]


# Part 3: Indexing and Data Extraction

## Question 4: Bengaluru Store Analysis

Extract and display the complete sales row for Bengaluru.

Bengaluru is the first store, so its row index is 0.

In [12]:
bengaluru_sales = sales_data[0]

print("Bengaluru sales across all categories:")
print(bengaluru_sales)
# TAn f-string that prints category left-aligned (<) padded to 12 characters wide, followed by :  and the value.
print("zip() takes two (or more) sequences and combines them into pairs, matching items by position: ")
for category, value in zip(categories, bengaluru_sales):
    print(f"{category:<12}: {value}")

Bengaluru sales across all categories:
[850000 420000 310000 275000 190000 225000]
zip() takes two (or more) sequences and combines them into pairs, matching items by position: 
Electronics : 850000
Groceries   : 420000
Clothing    : 310000
Furniture   : 275000
Beauty      : 190000
Sports      : 225000


## Question 5: Mumbai Cost Analysis

Extract the total cost incurred by the Mumbai store for all product categories.

Mumbai is the fourth store, so its row index is 3.

In [13]:
mumbai_cost = cost_data[3]

print("Mumbai cost across all categories:")
print(mumbai_cost)

print()
for x, y in zip(categories, mumbai_cost):
    print(f"{x:<12}: {y}")

print("\nTotal Mumbai cost:", mumbai_cost.sum())

Mumbai cost across all categories:
[790000 390000 265000 250000 165000 205000]

Electronics : 790000
Groceries   : 390000
Clothing    : 265000
Furniture   : 250000
Beauty      : 165000
Sports      : 205000

Total Mumbai cost: 2065000


## Question 6: Electronics Sales Across Stores

Extract the Electronics sales column from `sales_data`.

`[:, 0]` means every row, column 0 - the colon selects all stores.

In [14]:
electronics_sales = sales_data[:, 0]

print("Electronics sales across all stores:")
print(electronics_sales)

print()
for store, value in zip(stores, electronics_sales):
    print(f"{store:<11}: {value}")

Electronics sales across all stores:
[ 850000  780000  920000 1050000  690000]

Bengaluru  : 850000
Hyderabad  : 780000
Chennai    : 920000
Mumbai     : 1050000
Pune       : 690000


## Question 7: Clothing Cost Across Stores

Extract the Clothing cost for every store from `cost_data`.

Clothing is the third category, so the column index is 2.

In [15]:
clothing_cost = cost_data[:, 2]

print("Clothing cost across all stores:")
print(clothing_cost)

print()
for store, value in zip(stores, clothing_cost):
    print(f"{store:<11}: {value}")

Clothing cost across all stores:
[220000 210000 245000 265000 205000]

Bengaluru  : 220000
Hyderabad  : 210000
Chennai    : 245000
Mumbai     : 265000
Pune       : 205000


## Question 8: Hyderabad Furniture Performance

Find the Furniture sales, cost and profit for Hyderabad.

Hyderabad is row 1 and Furniture is column 3, so a single `[1, 3]` index reaches the
exact value.

In [16]:
furniture_sales = sales_data[1, 3]
furniture_cost = cost_data[1, 3]
furniture_profit = furniture_sales - furniture_cost

print("Store   : Hyderabad")
print("Category: Furniture")
print("Sales   :", furniture_sales)
print("Cost    :", furniture_cost)
print("Profit  :", furniture_profit)

Store   : Hyderabad
Category: Furniture
Sales   : 310000
Cost    : 225000
Profit  : 85000


## Question 9: Chennai Category Range

Extract Chennai's sales for Groceries, Clothing and Furniture using array slicing.

Chennai is row 2. Those three categories sit at columns 1, 2 and 3, so the slice
`1:4` covers them - the stop index is excluded.

In [17]:
chennai_range = sales_data[2, 1:4]

print("Chennai sales for Groceries, Clothing and Furniture:")
print(chennai_range)

print()
for category, value in zip(categories[1:4], chennai_range):
    print(f"{category:<12}: {value}")

Chennai sales for Groceries, Clothing and Furniture:
[390000 340000 260000]

Groceries   : 390000
Clothing    : 340000
Furniture   : 260000


## Question 10: Selected Store Analysis

Extract sales for Bengaluru, Chennai and Pune, including only Electronics, Clothing
and Beauty. Use advanced indexing.

`np.ix_()` builds the row-column grid so the selected rows and columns cross correctly.
Passing two plain lists instead would pair them element by element and return only
three values.

In [19]:
selected_stores = [0, 2, 4]
selected_categories = [0, 2, 4]

subset = sales_data[np.ix_(selected_stores, selected_categories)]

print("Selected subset:")
print(subset)
 # Each item is	One number (390000)	One row ([850000, 310000, 190000]""
print()
#"Printed via	"{value}""	row[0], row[1], row[2]")
print(f"{'Store':<12}{'Electronics':>13}{'Clothing':>11}{'Beauty':>9}")
for store_index, row in zip(selected_stores, subset):
    print(f"{stores[store_index]:<12}{row[0]:>13}{row[1]:>11}{row[2]:>9}")

Selected subset:
[[850000 310000 190000]
 [920000 340000 185000]
 [690000 280000 175000]]

Store         Electronics   Clothing   Beauty
Bengaluru          850000     310000   190000
Chennai            920000     340000   185000
Pune               690000     280000   175000


# Part 4: Sales Aggregation

## Question 11: Company-Wide Sales

Calculate the total sales revenue generated by all stores and all categories.

Calling `.sum()` with no axis collapses the entire array to a single value.

In [21]:
total_company_sales = sales_data.sum()

print("Total company-wide sales:", total_company_sales)

Total company-wide sales: 11675000


## Question 12: Store-Wise Sales

Calculate total sales revenue for each store and display the result with store names.

`axis=1` collapses the columns, leaving one total per row (store).

In [22]:
store_sales = sales_data.sum(axis=1)

for store, total in zip(stores, store_sales):
    print(f"{store}: {total}")

Bengaluru: 2270000
Hyderabad: 2295000
Chennai: 2310000
Mumbai: 2820000
Pune: 1980000


## Question 13: Category-Wise Sales

Calculate total sales for each product category across all stores.

`axis=0` collapses the rows, leaving one total per column (category).

In [23]:
category_sales = sales_data.sum(axis=0)

for category, total in zip(categories, category_sales):
    print(f"{category:<12}: {total}")

Electronics : 4290000
Groceries   : 2185000
Clothing    : 1600000
Furniture   : 1415000
Beauty      : 1010000
Sports      : 1175000


## Question 14: Average Sales Per Store

Calculate the average sales generated by each store across all six product categories.

In [24]:
store_average = sales_data.mean(axis=1)

for store, average in zip(stores, store_average):
    print(f"{store:<11}: {average:,.2f}")

Bengaluru  : 378,333.33
Hyderabad  : 382,500.00
Chennai    : 385,000.00
Mumbai     : 470,000.00
Pune       : 330,000.00


## Question 15: Average Sales Per Category

Calculate the average sales of each product category across the five stores.

In [25]:
category_average = sales_data.mean(axis=0)

for category, average in zip(categories, category_average):
    print(f"{category:<12}: {average:,.2f}")

Electronics : 858,000.00
Groceries   : 437,000.00
Clothing    : 320,000.00
Furniture   : 283,000.00
Beauty      : 202,000.00
Sports      : 235,000.00


## Question 16: Highest-Selling Store

Identify the index, name and total sales of the store with the highest total sales
using `np.argmax()`.

`argmax` returns the **position** of the largest value, which is then used to look up
the store name.

In [26]:
store_sales = sales_data.sum(axis=1)
best_index = np.argmax(store_sales)

print("Index of highest-selling store:", best_index)
print("Store name                    :", stores[best_index])
print("Total sales                   :", store_sales[best_index])

Index of highest-selling store: 3
Store name                    : Mumbai
Total sales                   : 2820000


## Question 17: Lowest-Selling Store

Identify the store with the lowest overall sales using `np.argmin()`.

In [27]:
store_sales = sales_data.sum(axis=1)
worst_index = np.argmin(store_sales)

print("Index of lowest-selling store:", worst_index)
print("Store name                   :", stores[worst_index])
print("Total sales                  :", store_sales[worst_index])

Index of lowest-selling store: 4
Store name                   : Pune
Total sales                  : 1980000


## Question 18: Highest-Selling Category

Find the product category that generated the highest total sales across the company.

In [28]:
category_sales = sales_data.sum(axis=0)
best_category_index = np.argmax(category_sales)

print("Highest-selling category:", categories[best_category_index])
print("Total sales             :", category_sales[best_category_index])

Highest-selling category: Electronics
Total sales             : 4290000


## Question 19: Lowest-Selling Category

Find the product category with the lowest total sales across all stores.

In [29]:
category_sales = sales_data.sum(axis=0)
worst_category_index = np.argmin(category_sales)

print("Lowest-selling category:", categories[worst_category_index])
print("Total sales            :", category_sales[worst_category_index])

Lowest-selling category: Beauty
Total sales            : 1010000


# Part 5: Cost Analysis

## Question 20: Total Company Cost

Calculate the total cost incurred by SmartMart across all stores and product categories.

In [30]:
total_company_cost = cost_data.sum()

print("Total company-wide cost:", total_company_cost)
print(f"Formatted: {total_company_cost:,}")

Total company-wide cost: 8600000
Formatted: 8,600,000


## Question 21: Store-Wise Cost

Calculate the total cost incurred by each store.

In [31]:
store_cost = cost_data.sum(axis=1)

for store, total in zip(stores, store_cost):
    print(f"{store:<11}: {total:,}")

Bengaluru  : 1,665,000
Hyderabad  : 1,685,000
Chennai    : 1,710,000
Mumbai     : 2,065,000
Pune       : 1,475,000


## Question 22: Category-Wise Cost

Calculate the total cost incurred for each product category across all stores.

In [32]:
category_cost = cost_data.sum(axis=0)

for category, total in zip(categories, category_cost):
    print(f"{category:<12}: {total:,}")

Electronics : 3,250,000
Groceries   : 1,660,000
Clothing    : 1,145,000
Furniture   : 1,045,000
Beauty      : 665,000
Sports      : 835,000


## Question 23: Most Expensive Store

Identify the store with the highest total operating cost.

In [33]:
store_cost = cost_data.sum(axis=1)
highest_cost_index = np.argmax(store_cost)

print("Most expensive store:", stores[highest_cost_index])
print("Total cost          :", store_cost[highest_cost_index])

Most expensive store: Mumbai
Total cost          : 2065000


## Question 24: Lowest-Cost Store

Identify the store with the lowest total cost.

In [34]:
store_cost = cost_data.sum(axis=1)
lowest_cost_index = np.argmin(store_cost)

print("Lowest-cost store:", stores[lowest_cost_index])
print("Total cost       :", store_cost[lowest_cost_index])

Lowest-cost store: Pune
Total cost       : 1475000


## Question 25: Most Expensive Product Category

Determine which product category has the highest total cost across all stores.

In [35]:
category_cost = cost_data.sum(axis=0)
highest_category_index = np.argmax(category_cost)

print("Most expensive category:", categories[highest_category_index])
print("Total cost             :", category_cost[highest_category_index])

Most expensive category: Electronics
Total cost             : 3250000


# Part 6: Profit Analysis Using Two Arrays

## Question 26: Profit Matrix

Calculate the profit for every store and product category using
`profit_data = sales_data - cost_data`, then display the complete profit matrix.

Both arrays share the same `(5, 6)` shape, so the subtraction happens element by
element without any loop.

In [37]:
profit_data = sales_data - cost_data

print("Profit matrix:")
print(profit_data)

print()
#print(f"{'Store':<12}" + "".join(f"{c:>13}" for c in categories))
#for store, row in zip(stores, profit_data):
    #print(f"{store:<12}" + "".join(f"{value:>13}" for value in row))

Profit matrix:
[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]



## Question 27: Store-Wise Profit

Calculate the total profit generated by each store.

In [38]:
store_profit = profit_data.sum(axis=1)

for store, total in zip(stores, store_profit):
    print(f"{store:<11}: {total:,}")

Bengaluru  : 605,000
Hyderabad  : 610,000
Chennai    : 600,000
Mumbai     : 755,000
Pune       : 505,000


## Question 28: Category-Wise Profit

Calculate the total profit generated by each product category.

In [39]:
category_profit = profit_data.sum(axis=0)

for category, total in zip(categories, category_profit):
    print(f"{category:<12}: {total:,}")

Electronics : 1,040,000
Groceries   : 525,000
Clothing    : 455,000
Furniture   : 370,000
Beauty      : 345,000
Sports      : 340,000


## Question 29: Most Profitable Store

Identify the store with the highest total profit and display its name, total sales,
total cost and total profit.

In [ ]:
store_profit = profit_data.sum(axis=1)
best_index = np.argmax(store_profit)

print("Store name  :", stores[best_index])
print("Total sales best store :", sales_data[best_index].sum())
print("Total cost  best store :", cost_data[best_index].sum())
print("Total profit of Best Store :", store_profit[best_index])

Store name  : Mumbai
Total sales : 2820000
Total cost  : 2065000
Total profit of Best Store : 755000


## Question 30: Least Profitable Store

Identify the store that generated the lowest total profit.

In [43]:
store_profit = profit_data.sum(axis=1)
worst_index = np.argmin(store_profit)

print("Store name  :", stores[worst_index])
print("Total sales :", sales_data[worst_index].sum())
print("Total cost  :", cost_data[worst_index].sum())
print("Total profit:", store_profit[worst_index])

Store name  : Pune
Total sales : 1980000
Total cost  : 1475000
Total profit: 505000


## Question 31: Most Profitable Category

Find the category with the highest total profit across all stores.

In [44]:
category_profit = profit_data.sum(axis=0)
best_category_index = np.argmax(category_profit)

print("Most profitable category:", categories[best_category_index])
print("Total profit            :", category_profit[best_category_index])

Most profitable category: Electronics
Total profit            : 1040000


## Question 32: Least Profitable Category

Find the category with the lowest total profit.

In [45]:
category_profit = profit_data.sum(axis=0)
worst_category_index = np.argmin(category_profit)

print("Least profitable category:", categories[worst_category_index])
print("Total profit             :", category_profit[worst_category_index])

Least profitable category: Sports
Total profit             : 340000


## Question 33: Maximum Individual Profit

Find the highest profit from any single store-category combination and display the
profit amount, store name and category. Use `np.unravel_index()`.

`argmax` returns a position in the **flattened** array. `unravel_index` converts that
flat number back into a row and column pair.

In [48]:
print("profit_data :",profit_data)
flat_position = np.argmax(profit_data)
print("flat_position :",flat_position)
row, column = np.unravel_index(flat_position, profit_data.shape)

print("Flat position   :", flat_position)
print("Row, column     :", (row, column))
print("Profit amount   :", profit_data[row, column])
print("Store name      :", stores[row])
print("Product category:", categories[column])

profit_data : [[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]
flat_position : 18
Flat position   : 18
Row, column     : (3, 0)
Profit amount   : 260000
Store name      : Mumbai
Product category: Electronics


## Question 34: Minimum Individual Profit

Find the smallest profit from a store-category combination and display the
corresponding store and category.

In [49]:
flat_position = np.argmin(profit_data)
row, column = np.unravel_index(flat_position, profit_data.shape)

print("Profit amount   :", profit_data[row, column])
print("Store name      :", stores[row])
print("Product category:", categories[column])

Profit amount   : 55000
Store name      : Pune
Product category: Furniture


# Part 7: Profit Margin Analysis

## Question 35: Profit Margin Matrix

Calculate the profit margin percentage for every store-category combination using
`(profit_data / sales_data) * 100`, rounded to two decimal places.

In [50]:
profit_margin = np.round((profit_data / sales_data) * 100, 2)

print("Profit margin matrix (%):")
print(profit_margin)

print()
print(f"{'Store':<12}" + "".join(f"{c:>13}" for c in categories))
for store, row in zip(stores, profit_margin):
    print(f"{store:<12}" + "".join(f"{value:>13}" for value in row))

Profit margin matrix (%):
[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]

Store         Electronics    Groceries     Clothing    Furniture       Beauty       Sports
Bengaluru           24.71         25.0        29.03        25.45        34.21        28.89
Hyderabad           24.36        23.91        28.81        27.42        33.33        29.17
Chennai             23.91        24.36        27.94         25.0        35.14        27.91
Mumbai              24.76        23.53        29.33        27.54         34.0        29.31
Pune                23.19        23.46        26.79        24.44        34.29        29.27


## Question 36: Store-Wise Profit Margin

Calculate the overall profit margin percentage for each store using
`Total Store Profit / Total Store Sales x 100`.

The totals are summed **first**, then divided - averaging the individual margins would
give a different and less accurate figure.

In [54]:
store_sales = sales_data.sum(axis=1)
store_profit = profit_data.sum(axis=1)
store_margin = np.round((store_profit / store_sales) * 100, 2)

for store, margin in zip(stores, store_margin):
    print(f"{store:<11}: {margin} %")
print("-"* 30)
for store, margin in zip(stores, store_margin):
     print(f"{store}: {margin} %")


Bengaluru  : 26.65 %
Hyderabad  : 26.58 %
Chennai    : 25.97 %
Mumbai     : 26.77 %
Pune       : 25.51 %
------------------------------
Bengaluru: 26.65 %
Hyderabad: 26.58 %
Chennai: 25.97 %
Mumbai: 26.77 %
Pune: 25.51 %


## Question 37: Category-Wise Profit Margin

Calculate the overall profit margin percentage for each product category.

In [55]:
category_sales = sales_data.sum(axis=0)
category_profit = profit_data.sum(axis=0)
category_margin = np.round((category_profit / category_sales) * 100, 2)

for category, margin in zip(categories, category_margin):
    print(f"{category:<12}: {margin} %")

Electronics : 24.24 %
Groceries   : 24.03 %
Clothing    : 28.44 %
Furniture   : 26.15 %
Beauty      : 34.16 %
Sports      : 28.94 %


## Question 38: Best Store by Profit Margin

Identify the store with the highest overall profit margin.

In [ ]:
store_margin = np.round((profit_data.sum(axis=1) / sales_data.sum(axis=1)) * 100, 2)
best_index = np.argmax(store_margin)
print("Best store by profit margin:", stores[best_index])
print("Profit margin              :", store_margin[best_index], "%")

Best store by profit margin: Mumbai
Profit margin              : 26.77 %


## Question 39: Best Category by Profit Margin

Identify the product category with the highest profit margin.

In [57]:
category_margin = np.round((profit_data.sum(axis=0) / sales_data.sum(axis=0)) * 100, 2)
best_index = np.argmax(category_margin)

print("Best category by profit margin:", categories[best_index])
print("Profit margin                 :", category_margin[best_index], "%")

Best category by profit margin: Beauty
Profit margin                 : 34.16 %


## Question 40: Low-Margin Transactions

Management considers a profit margin below 22% to be weak. Find all store-category
combinations below that threshold and display the store, category, sales, cost, profit
and profit margin. Use Boolean indexing.

`np.where()` on a Boolean matrix returns two arrays - the row positions and the column
positions of every `True` - which are then paired to read the store and category names.

In [58]:
profit_margin = np.round((profit_data / sales_data) * 100, 2)
low_margin_mask = profit_margin < 22
print("low_margin_mask",low_margin_mask)

rows, cols = np.where(low_margin_mask)

print("Number of weak combinations:", low_margin_mask.sum())
print()
print(f"{'Store':<12}{'Category':<13}{'Sales':>10}{'Cost':>10}{'Profit':>10}{'Margin':>9}")
print("-" * 64)
for r, c in zip(rows, cols):
    print(f"{stores[r]:<12}{categories[c]:<13}{sales_data[r, c]:>10}"
          f"{cost_data[r, c]:>10}{profit_data[r, c]:>10}{profit_margin[r, c]:>8} %")

low_margin_mask [[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]
Number of weak combinations: 0

Store       Category          Sales      Cost    Profit   Margin
----------------------------------------------------------------


# Part 8: Boolean Filtering

## Question 41: High Sales Values

Find all sales values greater than 5,00,000.

A comparison on an array produces a Boolean mask of the same shape. Using that mask as
an index returns only the values where it is `True`.

In [59]:
high_sales_mask = sales_data > 500000
high_sales_values = sales_data[high_sales_mask]

print("Boolean mask:")
print(high_sales_mask)

print("\nHigh sales values:", high_sales_values)
print("Count:", high_sales_values.size)

rows, cols = np.where(high_sales_mask)
print(rows,cols)
print()
for r, c in zip(rows, cols):
    print(f"{stores[r]:<12}{categories[c]:<13}{sales_data[r, c]:>10}")

Boolean mask:
[[ True False False False False False]
 [ True False False False False False]
 [ True False False False False False]
 [ True  True False False False False]
 [ True False False False False False]]

High sales values: [ 850000  780000  920000 1050000  510000  690000]
Count: 6
[0 1 2 3 3 4] [0 0 0 0 1 0]

Bengaluru   Electronics      850000
Hyderabad   Electronics      780000
Chennai     Electronics      920000
Mumbai      Electronics     1050000
Mumbai      Groceries        510000
Pune        Electronics      690000


## Question 42: Low Sales Values

Find all sales values below 2,00,000.

In [60]:
low_sales_mask = sales_data < 200000
low_sales_values = sales_data[low_sales_mask]

print("Low sales values:", low_sales_values)
print("Count:", low_sales_values.size)

rows, cols = np.where(low_sales_mask)
print()
for r, c in zip(rows, cols):
    print(f"{stores[r]:<12}{categories[c]:<13}{sales_data[r, c]:>10}")

Low sales values: [190000 185000 175000]
Count: 3

Bengaluru   Beauty           190000
Chennai     Beauty           185000
Pune        Beauty           175000


## Question 43: High Profit Values

Find all store-category combinations where profit is greater than 1,50,000.

In [61]:
high_profit_mask = profit_data > 150000

print("High profit values:", profit_data[high_profit_mask])
print("Count:", high_profit_mask.sum())
## using sum or size return the same value here for count 
rows, cols = np.where(high_profit_mask)
print()
for r, c in zip(rows, cols):
    print(f"{stores[r]:<12}{categories[c]:<13}{profit_data[r, c]:>10}")

High profit values: [210000 190000 220000 260000 160000]
Count: 5

Bengaluru   Electronics      210000
Hyderabad   Electronics      190000
Chennai     Electronics      220000
Mumbai      Electronics      260000
Pune        Electronics      160000


## Question 44: Moderate Sales Range

Find sales values between 2,50,000 and 5,00,000 using `np.logical_and()`.

Python's `and` keyword cannot combine two arrays, so `np.logical_and()` is used to
apply both conditions element by element.

In [62]:
moderate_mask = np.logical_and(sales_data >= 250000, sales_data <= 500000)
moderate_values = sales_data[moderate_mask]

print("Moderate sales values:", moderate_values)
print("Count:", moderate_values.size)

rows, cols = np.where(moderate_mask)
print()
for r, c in zip(rows, cols):
    print(f"{stores[r]:<12}{categories[c]:<13}{sales_data[r, c]:>10}")

Moderate sales values: [420000 310000 275000 460000 295000 310000 390000 340000 260000 375000
 345000 250000 290000 405000 280000]
Count: 15

Bengaluru   Groceries        420000
Bengaluru   Clothing         310000
Bengaluru   Furniture        275000
Hyderabad   Groceries        460000
Hyderabad   Clothing         295000
Hyderabad   Furniture        310000
Chennai     Groceries        390000
Chennai     Clothing         340000
Chennai     Furniture        260000
Mumbai      Clothing         375000
Mumbai      Furniture        345000
Mumbai      Beauty           250000
Mumbai      Sports           290000
Pune        Groceries        405000
Pune        Clothing         280000


## Question 45: Premium Performance

A combination is premium when sales are above 5,00,000 **and** profit is above
1,50,000. Find all premium-performing combinations.

The `&` operator combines two Boolean arrays element by element. Each condition needs
its own brackets because `&` binds tighter than `>`.

In [64]:
premium_mask = (sales_data > 500000) & (profit_data > 150000)
print("premium_mask :",premium_mask)
print("Number of premium combinations:", premium_mask.sum())
print()
print(f"{'Store':<12}{'Category':<13}{'Sales':>10}{'Profit':>10}")
print("-" * 45)

rows, cols = np.where(premium_mask)
for r, c in zip(rows, cols):
    print(f"{stores[r]:<12}{categories[c]:<13}{sales_data[r, c]:>10}{profit_data[r, c]:>10}")

premium_mask : [[ True False False False False False]
 [ True False False False False False]
 [ True False False False False False]
 [ True False False False False False]
 [ True False False False False False]]
Number of premium combinations: 5

Store       Category          Sales    Profit
---------------------------------------------
Bengaluru   Electronics      850000    210000
Hyderabad   Electronics      780000    190000
Chennai     Electronics      920000    220000
Mumbai      Electronics     1050000    260000
Pune        Electronics      690000    160000


## Question 46: Underperforming Combinations

A combination is underperforming when sales are below 2,50,000 **and** the profit
margin is below 25%.

In [65]:
profit_margin = np.round((profit_data / sales_data) * 100, 2)
underperforming_mask = (sales_data < 250000) & (profit_margin < 25)

print("Number of underperforming combinations:", underperforming_mask.sum())
print()
print(f"{'Store':<12}{'Category':<13}{'Sales':>10}{'Margin':>9}")
print("-" * 44)

rows, cols = np.where(underperforming_mask)
for r, c in zip(rows, cols):
    print(f"{stores[r]:<12}{categories[c]:<13}{sales_data[r, c]:>10}{profit_margin[r, c]:>8} %")

Number of underperforming combinations: 1

Store       Category          Sales   Margin
--------------------------------------------
Pune        Furniture        225000   24.44 %


## Question 47: Category Performance Classification

Classify every sales value as `"High"` (at least 5,00,000), `"Medium"` (2,50,000 to
4,99,999) or `"Low"` (below 2,50,000). Use `np.select()`.

`np.select()` checks the condition list in order and applies the first match, so the
conditions do not need to exclude one another manually.

In [67]:
conditions = [
    sales_data >= 500000,
    sales_data >= 250000,
    sales_data < 250000
]

labels = ["High", "Medium", "Low"]

print("conditions :",conditions)
classification = np.select(conditions, labels, default="Unknown")

print("Classification matrix:")
print(classification)

print()
print(f"{'Store':<12}" + "".join(f"{c:>13}" for c in categories))
for store, row in zip(stores, classification):
    print(f"{store:<12}" + "".join(f"{value:>13}" for value in row))

print("np.select() does NOT process one entire Boolean array and then move to the next array. Instead, conceptually, it looks at the same position across all condition arrays, decides which condition is the first True, and puts the corresponding label at that position.")
values, counts = np.unique(classification, return_counts=True)
for label, count in zip(values, counts):
    print(f"{label:<8}: {count}")

conditions : [array([[ True, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [ True,  True, False, False, False, False],
       [ True, False, False, False, False, False]]), array([[ True,  True,  True,  True, False, False],
       [ True,  True,  True,  True, False, False],
       [ True,  True,  True,  True, False, False],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True, False, False, False]]), array([[False, False, False, False,  True,  True],
       [False, False, False, False,  True,  True],
       [False, False, False, False,  True,  True],
       [False, False, False, False, False, False],
       [False, False, False,  True,  True,  True]])]
Classification matrix:
[['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'High' 'Medium' 'Medium' 'Medium' 'M